src/jointcal.cc
tests/test_wcs.cc

Cleanup floating point exception management, but keep it as GNU only. May be useful for future debugging, but the "portable" version of fenv.h that I proposed in RFC-158 was not as portable as I'd hoped.

cleanup floating point exception management

---

python/lsst/jointcal/jointcal.py

Forgot about one commit: fixed some excessive line lengths.

fix excessive line length.

---

python/lsst/jointcal/jointcal.py
tests/test_jointcal_decam.py

Working version of a jointcal test for decam data, post-VisitInfo.

Jointcal test for decam Tickets/dm 6624

---

include/lsst/jointcal/AstromFit.h
include/lsst/jointcal/BaseStar.h
include/lsst/jointcal/FastFinder.h
include/lsst/jointcal/FittedStar.h
include/lsst/jointcal/Gtransfo.h
include/lsst/jointcal/MeasuredStar.h
include/lsst/jointcal/PhotomFit.h
include/lsst/jointcal/RefStar.h
include/lsst/jointcal/StarMatch.h
src/Associations.cc
src/AstroUtils.cc
src/AstromFit.cc
src/BaseStar.cc
src/ConstrainedPolyModel.cc
src/FastFinder.cc
src/FittedStar.cc
src/Gtransfo.cc
src/Histo4d.cc
src/ListMatch.cc
src/MeasuredStar.cc
src/PhotomFit.cc
src/Projectionhandler.cc
src/RefStar.cc
src/SimplePolyModel.cc
src/StarMatch.cc

The first commit fixes the segfault, while the second replaces NULL with nullptr everywhere plus some cleanups where an exception should have been raised instead. Hopefully that removes any other problems like the one that caused this in the first place.

Fix macOS clang segfaults and cleanup NULLs Tickets/dm 8057

---

bin.src/plot_jointcal_results.py
python/lsst/jointcal/utils.py
src/Associations.cc
tests/jointcalTestBase.py
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py
tests/test_jointcal_hsc.py
tests/test_jointcal_lsstSim.py

Moved the jointcal plotting and RMS calculation code out of the tests and into `utils.py`, and added a `bin/` script to make plots outside of test running (which will be helpful for working on plotting later). Also refactored testing base class.
`utils.py` doesn't have any tests, but the algorithms in it are pretty dumb, and should be replaced as part of DM-8664.

Improve jointcal plotting backend Tickets/dm 7444

---

bin.src/plot_jointcal_results.py
python/lsst/jointcal/utils.py
tests/jointcalTestBase.py
tests/test_jointcal_lsstSim.py

While writing the PA1 test for lsstSim, I discovered a bug that changed the results depending on whether it was run via unittest or from plot_jointcal_results.py. The photometric part of that is fixed (the astrometric part is a "feature" of data_ref ordering which is now noted, but probably not worth fixing).

Add lsstSim PA1 test and serious bugfix tickets/DM-8551

---

python/lsst/jointcal/jointcal.py

New code is much faster: 37s vs. 47s to run the lsstSim 2 and 10 visit tests together. The speed bump will be even higher when working with more visits and ccds, since the original code was O(N^2), while this is O(N)+O(1), in addition to fewer butler accesses.

fix slow jointcal output writing Tickets/DM-8978

---

include/lsst/jointcal/Associations.h
python/lsst/jointcal/jointcal.py
src/Associations.cc
tests/jointcalTestBase.py
tests/test_jointcal_hsc.py

cleanMatches looks like it was used to debug starMatchList: probably don't
need it any more.
Add tests for minMeasurements and matchCut, plus a test for 3 visits with the
default config, to test setting minMeasurements to 3 (since it obviously won't
work with only 2 visits).

DM-7070 Move consts from top of Associations.cc into JointcalConfig

---

include/lsst/jointcal/AstrometryFit.h
include/lsst/jointcal/CcdImage.h
include/lsst/jointcal/Gtransfo.h
include/lsst/jointcal/PhotometryFit.h
include/lsst/jointcal/StarMatch.h
python/lsst/jointcal/jointcal.py
python/lsst/jointcal/photometryFit.cc
src/AstrometryFit.cc
src/BaseStar.cc
src/CcdImage.cc
src/ConstrainedPolyModel.cc
src/Histo4d.cc
src/PhotometryFit.cc
src/SimplePhotometryModel.cc
src/SimplePolyModel.cc
src/SipToGtransfo.cc
src/StarMatch.cc

Searched for warnings with both `clang-800.0.38` on macOS and `gcc 5.4.0-6ubuntu1~16.04.4` on Linux.

DM-8750 cleanup jointcal compiler warnings

---

tests/jointcalTestBase.py

Without this, in pytest,  when CFHT tests run they define a "u" filter,
and when the DECam tests run they fail because the "u" filter
has already been defined.

DM-11614: Reset filter list before running each test

---

python/lsst/jointcal/dataIds.py
python/lsst/jointcal/utils.py
tests/test_wcs.cc

Use of NAXIS1,NAXIS2 is being too familiar with the output format.
lsst.afw.image.bboxFromMetadata allows us to abstract the format.
This is especially important once we activate compression.

DM-11332: use bboxFromMetadata instead of NAXIS1,NAXIS2

---

include/lsst/jointcal/Associations.h
include/lsst/jointcal/AstrometryFit.h
include/lsst/jointcal/FitterBase.h
include/lsst/jointcal/PhotometryFit.h
python/lsst/jointcal/fitter.cc
python/lsst/jointcal/jointcal.py
src/Associations.cc
src/AstrometryFit.cc
src/CcdImage.cc
src/FitterBase.cc
src/PhotometryFit.cc
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py

This should fix NaNs that sneak in via bad refractionAngle calculations, refcat sources with `flux=NaN or inf` or `fluxErr=NaN or inf or 0`, and cause early failure if chi2 is NaN before or during the fitting process. I also made some cleanups that helped me debug this but that we'll want for the future.

DM-12310 fix NaNs in photometry and astrometry

---

README
Readme.md
include/lsst/jointcal/Associations.h
include/lsst/jointcal/ConstrainedPhotometryModel.h
include/lsst/jointcal/ConstrainedPolyModel.h
include/lsst/jointcal/PhotometryModel.h
include/lsst/jointcal/SimplePhotometryModel.h
python/lsst/jointcal/astrometryModels.cc
python/lsst/jointcal/dataIds.py
python/lsst/jointcal/jointcal.py
src/ConstrainedPolyModel.cc
src/FitterBase.cc
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py

This is a bit of a grab-bag of changes, but it was spurred by some changes I needed for DM-11785, and some bugs in the fitting code discovered by @boutigny and @PierreAstier .
Jointcal now raises an exception if there's a CHOLMOD error, instead of printing a message and continuing on. Making that error more obvious seems like the right approach.

DM-12602 fitting bugfixes and other cleanups

---

python/lsst/jointcal/chi2.cc
python/lsst/jointcal/photometryModels.cc
python/lsst/jointcal/photometryTransfo.cc
python/lsst/jointcal/star.cc

This PR replaces trivial pybind11 wrappers of operator<< with calls to `wrapOutputOp`, which is introduced in lsst/utils#47. Non-trivial wrappers (typically ones that add extra information to `__repr__`) are left untouched.

DM-10066: Provide utility function for wrapping operator<<

---

src/ConstrainedPhotometryModel.cc

DM-12447: Remove TransformMap.transform, Camera.transform and Detector.transform

---

Readme.md
python/lsst/jointcal/jointcal.py
tests/test_astrometryModel.py
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py
tests/test_jointcal_hsc.py
tests/test_jointcal_lsstSim.py

This can't be merged until DM-9832 is finished.

DM-14155 make jointcal compatible with other source selectors

---

tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py

My cfht test data doesn't exhibit differences on different platforms, and can be used to implement the same set of tests, so I've moved those tests from decam to cfht, and skipped the centos6 failing decam test.

DM-14552 Move tests from decam to cfht

---

include/lsst/jointcal/Gtransfo.h
include/lsst/jointcal/SimpleAstrometryMapping.h
src/ConstrainedAstrometryModel.cc
src/Gtransfo.cc
src/SimpleAstrometryModel.cc

for objects that have it, e.g. GtransfoLin and TanRaDec2Pix.
Also use invert() instead of deprecated inverted() for objects
from other packages.

DM-15139: Rename invert() and getInverse() to inverted()

---

tests/test_jointcal_cfht.py

The data in testdata_jointcal used in this test was processed pre- RFC-498
(ticket DM-14997) and thus has the old flag names.  This sets the config in
the test to point to the old name appropriate for the current datasets in
testdata_jointcal.
This should be removed if the data in testdata_jointcal are ever reprocessed
post-RFC-498.

DM-14997: Implement RFC-498: homogenize naming of calibration flags

---

tests/jointcalTestBase.py
tests/test_jointcal_cfht_minimal.py
tests/test_jointcal_hsc.py
tests/test_jointcal_lsstSim.py

All of the cfht_minimal tests were using `JointcalTestCFHTMinimal/run` for
their output directories, which occasionally caused a race (though exactly
why I'm not certain). This fixes them to use the correct, named-after-method
directories.

DM-15513 Fix bug in caller naming to prevent race condition

---

setup.cfg
tests/config/config.py
tests/config/hsc-config.py
tests/jointcalTestBase.py
tests/test_jointcal_cfht.py
tests/test_jointcal_cfht_minimal.py
tests/test_jointcal_decam.py
tests/test_jointcal_hsc.py
tests/test_jointcal_lsstSim.py

Many unit tests in this package retarget LoadAstrometryNetObjectsTask
and then test JointcalTask with entrypoint `parseAndRun()`, the
CommandlineTask parser, which loads and applies the relevant
obs_package config overrides.
Move the astrometry and photometry RefObjLoader retargetting to a
configfile so it is applied last and the unit tests are not
affected by the obs_package configs,

DM-15606: Move unit tests' retargetting a.net to configfile

---

python/lsst/jointcal/jointcal.py
setup.cfg
tests/SConscript

This was generating a flake8 warning before.

DM-16296: Remove escape of % in string

---

include/lsst/jointcal/AstrometryModel.h
include/lsst/jointcal/CcdImage.h
include/lsst/jointcal/ConstrainedAstrometryModel.h
include/lsst/jointcal/Gtransfo.h
include/lsst/jointcal/ProjectionHandler.h
include/lsst/jointcal/SimpleAstrometryMapping.h
include/lsst/jointcal/SimpleAstrometryModel.h
python/lsst/jointcal/astrometryModels.cc
python/lsst/jointcal/ccdImage.cc
python/lsst/jointcal/gtransfo.cc
src/Associations.cc
src/AstrometryFit.cc
src/CcdImage.cc
src/ConstrainedAstrometryModel.cc
src/Gtransfo.cc
src/Projectionhandler.cc
src/SimpleAstrometryModel.cc
tests/test_astrometryModel.py
tests/test_ccdImage.py
tests/test_wcs.cc

* Rename sky2TP->skyToTangentPlane
* Rename other ccdImage tangent plane/pixel methods and members: `X2Y`->`XToY`
and cleanup TP->TangentPlane, CTP->CommonTangentPlane, etc.
Rename gtransfo subclasses:
* TanPix2RaDec->TanPixelToRaDec
* TanRaDec2Pix->TanRaDecToPixel
* TanSipPix2RaDec->TanSipPixelToRaDec

DM-13270: Cleanup ccdImage and gtransfo APIs

---

python/lsst/jointcal/jointcal.py
tests/config/cfht-flagged-config.py
tests/config/config.py
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py
tests/test_jointcal_hsc.py

and limit to isolated stars with SNR > 10.
This config shows improvement in the photometric repeatability
and match to the reference catalog.
* Revert to astrometry source selector in unit tests
that check equality in metrics when jointcal run on testdata.
* Remove some now-redundant config overrides in those
affected unit tests.

DM-17830: Use only stars in internal jointcal fitting

---

include/lsst/jointcal/Associations.h
python/lsst/jointcal/associations.cc
python/lsst/jointcal/jointcal.py
python/lsst/jointcal/testUtils.py
src/Associations.cc
tests/test_jointcal.py
tests/test_jointcal_cfht.py
tests/test_jointcal_cfht_minimal.py
tests/test_jointcal_decam.py

This should fix the problem, and includes a test that demonstrates the fix.

DM-19802: Fix jointcal ra/dec bounding box calculations

---

tests/jointcalTestBase.py

In Astropy 4 the floating point scalar value from a `Quantity` is now a `numpy.float64` and not a `float`.  The test for float fails. Fix by checking `isinstance` `float`.

DM-22386: Look for subclasses of float and not exactly a float

---

ups/jointcal.table

This is a special case.
We keep `eigen` for jointcal specifically because eigen in conda-forge does not have long support for the cholmod code.

DM-23835 - Remove third parties from code (use conda third-parties)

---

include/lsst/jointcal/FitterBase.h
python/lsst/jointcal/fitter.cc
python/lsst/jointcal/jointcal.py
src/FitterBase.cc
tests/test_jointcal_cfht.py

Truncate iterations of outlier rejection when the outlier cut criterion
changes by less than the allowed tolerance, given by the jointcal.py
config parameter `astrometryOutlierRelativeTolerance`. This happens when
removing additional outliers stops significantly changing the model and
hence the chi2 distribution. The default behavior is unchanged: when
`astrometryOutlierRelativeTolerance`=0 iterations of outlier rejection
continue until there are no more outliers.

DM-27083: Improve jointcal outlier rejection

---

include/lsst/jointcal/Associations.h
include/lsst/jointcal/AstrometryFit.h
include/lsst/jointcal/BaseStar.h
include/lsst/jointcal/FatPoint.h
include/lsst/jointcal/FitterBase.h
include/lsst/jointcal/PhotometryFit.h
include/lsst/jointcal/Point.h
python/lsst/jointcal/associations.cc
python/lsst/jointcal/jointcal.py
src/Associations.cc
src/AstrometryFit.cc
src/FitterBase.cc
src/Histo2d.cc
src/Histo4d.cc
src/PhotometryFit.cc
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py
tests/test_jointcal_hsc.py

The new code here is not exercised by any existing tests, and it's not something I can readily mock up with a new test. It does allow us to try out an alternate fitting approach in DM-30252, and I hope that ticket produces a test case that uses this code.

DM-30254: Fix jointcal crash when doing outlier rejection on only the model

---

include/lsst/jointcal/Associations.h
include/lsst/jointcal/AstrometryFit.h
include/lsst/jointcal/BaseStar.h
include/lsst/jointcal/CcdImage.h
include/lsst/jointcal/FittedStar.h
include/lsst/jointcal/MeasuredStar.h
include/lsst/jointcal/PhotometryFit.h
include/lsst/jointcal/ProperMotion.h
include/lsst/jointcal/RefStar.h
python/lsst/jointcal/associations.cc
python/lsst/jointcal/ccdImage.cc
python/lsst/jointcal/jointcal.py
python/lsst/jointcal/star.cc
src/Associations.cc
src/AstrometryFit.cc
src/CcdImage.cc
src/FittedStar.cc
src/PhotometryFit.cc
src/ProperMotion.cc
tests/test_jointcal.py
tests/test_jointcal_cfht.py
tests/test_jointcal_decam.py
tests/test_jointcal_hsc.py
tests/test_star.py

As implemented on this ticket, the new PM corrections do not include PM uncertainty which will be done on DM-30383.

DM-24278: Apply proper motion to matched sources in Jointcal

---

tests/config/hsc-config.py

The default value of the astrometryOutlierRelativeTolerance config
parameter has been changed in obs_subaru, so the expected values of chi2
and ndof change in some tests.

DM-30534: Turn off config parameter from obs_subaru for tests

---

python/lsst/jointcal/jointcal.py

This works for both pre-RFC-807 and post-RFC-807 Source Tables.
The name of the index changed in RFC-807, but not the contents

DM-32030: Use index from dataframe as 'id' in afwTable

---

lib/SConscript
tests/test_star.py

Note that the astropy vs Rubin proper motion comparison test needed to be relaxed because the astropy value (used as a comparison) is varies depending on architecture.

DM-32487: Adjust flags and tests to support osx-arm64

---

python/lsst/jointcal/jointcal.py
tests/jointcalTestBase.py
tests/test_jointcal_hsc.py

Done jointly with @natelust  and @parejkoj

DM-29884: Fix exception in Gen3+applyColorTerms

---

tests/test_jointcal_decam.py

During construction of the DECam DRP pipeline, color terms were added.
This modified some of the numbers being tested against in jointcal. This
ticket updates these empirical numbers to match the new outputs.

DM-32430: Create DECam DRP Processing Pipeline

---

doc/lsst.jointcal/index.rst
python/lsst/jointcal/cameraGeometry.py

DM-32601 broke the pipelines build by not removing jointcal.utils from the automodapi block in index.rst.
This branch also adds an automodapi that was missed when a new module was added.

DM-32601-docfix: fix pipelines build

---

tests/test_jointcal.py

Building with python=3.10 reveals that this was always a typo, but now there's a check in python for common typos in `autospec`.  Huh!

DM-33487: Fix autospec typo in jointcal tests.

---

python/lsst/jointcal/jointcal.py
python/lsst/jointcal/testUtils.py
tests/jointcalTestBase.py
tests/test_astrometryModel.py
tests/test_ccdImage.py
tests/test_jointcal.py
tests/test_photometryModel.py

This PR removes remaining use of the obsolete `afw.image.Filter`, then replaces the deprecated `filterLabel` component with a new `filter` component backed by `afw.image.FilterLabel`.

DM-27177: Remove lsst.afw.image.Filter

---

include/lsst/jointcal/SimpleAstrometryMapping.h

This PR removes or rearranges Doxygen comments that were intended to be file-level but instead described namespaces.

DM-22823: Remove accidental Doxygen comments for namespaces

---

python/lsst/jointcal/jointcal.py

DM-35697: Use lsst.utils.timer.profile rather than deprecated pipe_base version

---

bin.src/plot_photoCalib.py
python/lsst/jointcal/cameraGeometry.py
python/lsst/jointcal/jointcal.py

* Remove unused gen2 code
* Use python logging in python code.

DM-35897: Minor gen2 and logging cleanup

---

python/lsst/jointcal/jointcal.py

After this is fully implemented in QG generation (DM-38498) this will allow us to remove the lookupFunction for reference catalog inputs.

DM-40322: Implement hook to define spatial bounds for prerequisites.
